// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKMeWEkW9sEXrCFyNBt4pb01zqTODB7sA',
    appId: '1:464284074940:web:eaaa24724cd2b1580ba1b9',
    messagingSenderId: '464284074940',
    projectId: 'tree-todo',
    authDomain: 'tree-todo.firebaseapp.com',
    storageBucket: 'tree-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_CYB1BEzcT_xj6ExKdj-kk7YXmpIWZE',
    appId: '1:464284074940:android:72943798fe5a2c640ba1b9',
    messagingSenderId: '464284074940',
    projectId: 'tree-todo',
    storageBucket: 'tree-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpaZ3K5mb8aKNM54Mfz2OeKJIZjGGVqo',
    appId: '1:464284074940:ios:c066c02acc34e4ff0ba1b9',
    messagingSenderId: '464284074940',
    projectId: 'tree-todo',
    storageBucket: 'tree-todo.appspot.com',
    iosBundleId: 'com.example.treeDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpaZ3K5mb8aKNM54Mfz2OeKJIZjGGVqo',
    appId: '1:464284074940:ios:122278901e8f094e0ba1b9',
    messagingSenderId: '464284074940',
    projectId: 'tree-todo',
    storageBucket: 'tree-todo.appspot.com',
    iosBundleId: 'com.example.treeDo.RunnerTests',
  );
}
